<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * One row per recording: who, where, how long, and the counters the list
 * filters on. The events themselves live on the storage disk (replay_chunks).
 * In a database-per-tenant app the four replay tables belong to the CENTRAL
 * database (session-replay.storage.connection).
 */
return new class extends Migration
{
    public function __construct()
    {
        $this->connection = config('session-replay.storage.connection');
    }

    public function up(): void
    {
        Schema::connection($this->connection)->create('replay_sessions', function (Blueprint $table) {
            $table->uuid('id')->primary(); // generated by the browser, one per tab and idle window
            $table->string('user_type')->nullable(); // strings, so integer, UUID and ULID keys all fit
            $table->string('user_id')->nullable();
            $table->string('tenant_type')->nullable();
            $table->string('tenant_id')->nullable();
            $table->string('impersonator_id')->nullable();
            $table->json('properties')->nullable(); // what the app attached when the page rendered (panel, plan…)
            $table->string('entry_url', 2048)->nullable();
            $table->string('user_agent', 512)->nullable();
            $table->string('device', 20)->nullable(); // desktop | tablet | mobile
            $table->unsignedSmallInteger('viewport_width')->nullable();
            $table->unsignedSmallInteger('viewport_height')->nullable();
            $table->unsignedInteger('page_count')->default(0);
            $table->unsignedInteger('event_count')->default(0);
            $table->unsignedInteger('chunk_count')->default(0);
            $table->unsignedBigInteger('bytes')->default(0); // as stored (gzip)
            $table->unsignedInteger('error_count')->default(0);
            $table->unsignedInteger('rage_click_count')->default(0);
            $table->unsignedInteger('lcp_ms')->nullable(); // worst of the recording
            $table->unsignedInteger('inp_ms')->nullable();
            $table->decimal('cls', 8, 4)->nullable();
            $table->unsignedBigInteger('active_ms')->default(0);
            $table->boolean('pinned')->default(false);
            $table->boolean('truncated')->default(false); // hit ingest.max_session_mb
            $table->timestamp('started_at')->nullable()->index();
            $table->timestamp('last_activity_at')->nullable()->index();
            $table->timestamps();

            $table->index(['user_type', 'user_id']);
            $table->index(['tenant_type', 'tenant_id']);
            $table->index(['tenant_type', 'tenant_id', 'started_at']); // a workspace's list, newest first
        });
    }

    public function down(): void
    {
        Schema::connection($this->connection)->dropIfExists('replay_sessions');
    }
};
